ARG NODE_IMAGE=node:24-alpine@sha256:d32cdf619f63fe0471182d08996dd516c6275bb5fd31ae06e55a570bd9e1ad43
FROM ${NODE_IMAGE}
WORKDIR /app
RUN npm init -y && npm install redis@4
COPY redis-rest-proxy.mjs .
EXPOSE 80
CMD ["node", "redis-rest-proxy.mjs"]
